In [4]:
marks=[34,54,89,23,45,67,88,90,12,49]
print("Original marks list:", marks)
type(marks)

Original marks list: [34, 54, 89, 23, 45, 67, 88, 90, 12, 49]


list

In [2]:
import numpy as np

In [5]:
marks=np.array(marks)
type(marks)

numpy.ndarray

In [7]:
a=np.zeros(5)

In [8]:
print(a.ndim)

1


In [13]:
b=np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
b.dtype

dtype('float64')

In [20]:
a=np.arange(1,20)

In [29]:
matrix=np.arange(1,16).reshape(3,5)

In [23]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
matrix.shape

(3, 3)

In [25]:
matrix.ndim

2

In [27]:
a=np.arange(1,20)
a.ndim

1

In [30]:
matrix.size

15

Indexing and Slicing


In [31]:
marks_array = np.array(marks)

In [32]:
marks_array

array([34, 54, 89, 23, 45, 67, 88, 90, 12, 49])

In [33]:
marks_array[0]

np.int64(34)

In [35]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
arr[2]

np.float64(0.0)

In [37]:
marks_array[-2]

np.int64(12)

In [38]:
marks_array[1:3]

array([54, 89])

In [39]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [44]:
matrix[1,4]

np.int64(10)

In [46]:
matrix[[0,2],[1,3]]

array([ 2, 14])

In [51]:
marks=np.arange(1,17).reshape(4,4)

In [52]:
marks

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
print(marks[0,1],marks[1,2],marks[2,-1],marks[3,0])

2 7 12 13


In [64]:
print(marks[[0,1,2,3],[1,2,-1,0]])

[ 2  7 12 13]


In [66]:
salary=np.array([45000,55000,60000,75000,80000])
new_salary=salary+5000

In [67]:
print(new_salary)

[50000 60000 65000 80000 85000]


In [70]:
salary=np.array([45000,55000,60000,75000,80000])
new_salary=salary*1.02

In [71]:
new_salary

array([45900., 56100., 61200., 76500., 81600.])

In [72]:
np.mean(new_salary)

np.float64(64260.0)

In [73]:
np.max(new_salary)

np.float64(81600.0)

In [74]:
np.min(new_salary)

np.float64(45900.0)

In [76]:
marks_array

array([34, 54, 89, 23, 45, 67, 88, 90, 12, 49])

In [87]:
pass_students=np.where(marks_array>=60,"pass","fail")

In [88]:
pass_students

array(['fail', 'fail', 'pass', 'fail', 'fail', 'pass', 'pass', 'pass',
       'fail', 'fail'], dtype='<U4')

Broadcasting in Numpy

In [90]:
price=np.array([100,200,300,400,500])
new_price=price+(price*0.18)

In [91]:
new_price

array([118., 236., 354., 472., 590.])

2d array manipulation using numpy

In [92]:
marks_2d=np.array([[34,54,89,23],[45,67,88,90],[12,49,78,56]])

In [93]:
marks_2d

array([[34, 54, 89, 23],
       [45, 67, 88, 90],
       [12, 49, 78, 56]])

In [95]:
marks_2d.mean(axis=1)

array([50.  , 72.5 , 48.75])

In [112]:
salary=np.ones(5,dtype=int)*2500

In [113]:
salary

array([2500, 2500, 2500, 2500, 2500])

In [101]:
marks2d=np.array([
    [
    34,54,89,23],
[
    45,67,88,90
],
[
    12,49,78,56
]])

In [102]:
marks2d.ndim

2

In [103]:
marks2d

array([[34, 54, 89, 23],
       [45, 67, 88, 90],
       [12, 49, 78, 56]])

In [105]:
marks2d.max(axis=0)

array([45, 67, 89, 90])

In [121]:
arr1=np.arange(50)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [122]:
arr1=arr1.reshape(10,5)

In [127]:
a=arr1.flatten()

In [128]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [130]:
a.ndim

1

In [ ]:
salary=np.array([45000,55000,60000,75000,80000])
tax=salary*0.10

In [134]:
tax

array([4500., 5500., 6000., 7500., 8000.])

In [137]:
result=[]
for i in salary:
    result.append(i*0.10)
result


[np.float64(4500.0),
 np.float64(5500.0),
 np.float64(6000.0),
 np.float64(7500.0),
 np.float64(8000.0)]

In [138]:
salary=np.array([45000,55000,60000,75000,80000])
tax=salary*0.10
print(tax)

[4500. 5500. 6000. 7500. 8000.]


Random Modulem

In [148]:
np.random.randint(1,9,size=1000)

array([1, 2, 4, 2, 6, 1, 6, 2, 8, 5, 3, 4, 4, 2, 1, 8, 1, 7, 2, 5, 5, 4,
       7, 6, 8, 2, 3, 7, 7, 7, 3, 2, 4, 7, 7, 3, 6, 8, 6, 8, 3, 1, 1, 7,
       2, 5, 3, 5, 1, 6, 5, 4, 2, 2, 8, 1, 7, 7, 8, 1, 6, 5, 7, 5, 2, 8,
       3, 8, 8, 7, 7, 7, 2, 5, 8, 1, 5, 1, 1, 2, 8, 3, 4, 8, 6, 2, 1, 5,
       2, 4, 5, 7, 2, 6, 5, 6, 3, 8, 4, 1, 2, 4, 7, 3, 4, 4, 6, 2, 3, 1,
       5, 2, 7, 4, 7, 5, 8, 6, 6, 5, 6, 4, 1, 8, 8, 5, 8, 2, 3, 4, 3, 6,
       6, 7, 3, 3, 8, 1, 1, 2, 1, 4, 8, 8, 3, 7, 3, 2, 4, 3, 1, 6, 2, 3,
       1, 2, 8, 8, 3, 5, 7, 7, 6, 3, 3, 4, 6, 3, 7, 3, 6, 1, 7, 2, 2, 2,
       4, 7, 6, 5, 5, 5, 1, 3, 3, 4, 1, 1, 2, 5, 7, 6, 1, 6, 7, 4, 2, 4,
       8, 5, 4, 4, 7, 7, 1, 1, 3, 7, 6, 7, 1, 1, 8, 3, 1, 5, 7, 1, 4, 1,
       4, 4, 4, 1, 8, 3, 6, 4, 8, 1, 6, 4, 3, 8, 5, 1, 3, 7, 7, 4, 1, 4,
       3, 4, 8, 6, 3, 5, 6, 8, 6, 1, 3, 7, 7, 8, 3, 7, 7, 4, 2, 6, 4, 1,
       2, 7, 8, 1, 3, 1, 6, 5, 3, 7, 4, 5, 7, 5, 5, 7, 3, 8, 6, 6, 5, 2,
       5, 2, 2, 2, 4, 3, 4, 5, 2, 4, 6, 8, 7, 4, 1,

In [146]:
np.random.rand(4,4)

array([[0.85775357, 0.39078711, 0.27276614, 0.38338476],
       [0.67548212, 0.0297747 , 0.32088915, 0.32676294],
       [0.02219417, 0.2784692 , 0.69806677, 0.56486726],
       [0.91342656, 0.36041354, 0.24863444, 0.27860756]])

In [2]:
pip install numpy

  Using cached numpy-2.4.0-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.0-cp312-cp312-win_amd64.whl (12.3 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
np.sum(a)

np.int64(15)

In [ ]:
a=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
total=0
for i in a:
    total+=i
print(total)
    
    


230


In [10]:
a=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
np.array(a).sum()

np.int64(230)

In [12]:
b=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
np.mean(a)

np.float64(8.518518518518519)

In [13]:
b=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
np.max(a)

np.int64(56)

In [14]:
b=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
np.min(a)

np.int64(1)

In [17]:
b=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
li=[]
for i in b:
    li.append([i*i])
print(li)


[[1], [4], [9], [16], [25], [25], [25], [36], [3136], [25], [16], [25], [25], [25], [25], [25], [25], [25], [3025], [36], [25], [36], [25], [36], [25], [25], [36]]


In [18]:
b=[1,2,3,4,5,5,5,6,56,5,4,5,5,5,5,5,5,5,55,6,5,6,5,6,5,5,6]
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.23606798, 2.23606798, 2.44948974, 7.48331477, 2.23606798,
       2.        , 2.23606798, 2.23606798, 2.23606798, 2.23606798,
       2.23606798, 2.23606798, 2.23606798, 7.41619849, 2.44948974,
       2.23606798, 2.44948974, 2.23606798, 2.44948974, 2.23606798,
       2.23606798, 2.44948974])

In [25]:
a=[4,6,9]
b=np.sqrt(a).astype(int)
print(b)
print(type(b))
print(b.dtype)

[2 2 3]
<class 'numpy.ndarray'>
int64


In [26]:
output=list(map(int,np.sqrt(a)))

In [28]:
output
type(output)

list

In [34]:
output=np.int64(np.sqrt(a))

In [35]:
output

array([2, 2, 3])

In [43]:
# 2 D
arr=np.array([[10,20,130],[10,20,30],[40,60,80]]) 

In [44]:
arr.ndim

2

In [45]:
arr

array([[ 10,  20, 130],
       [ 10,  20,  30],
       [ 40,  60,  80]])

In [46]:
np.sum(arr,axis=1)

array([160,  60, 180])

In [47]:
np.sum(arr,axis=0)

array([ 60, 100, 240])

In [48]:
np.mean(arr,axis=0)

array([20.        , 33.33333333, 80.        ])

In [51]:
np.min(arr,axis=0)

array([10, 20, 30])

In [53]:
# Boolean Indexing|
marks=np.array([[34,54,89,23],[45,67,88,90],[12,49,78,56]])
print(marks)

[[34 54 89 23]
 [45 67 88 90]
 [12 49 78 56]]


In [62]:
marks=np.array([50,60,50,30,28,31,41,40])
pass_students=np.where(marks>=40,"pass","fail")
pass_students

array(['pass', 'pass', 'pass', 'fail', 'fail', 'fail', 'pass', 'pass'],
      dtype='<U4')

In [63]:
marks=np.array([50,60,50,30,28,31,41,40])

In [64]:
marks

array([50, 60, 50, 30, 28, 31, 41, 40])

In [65]:
np.sort(marks)

array([28, 30, 31, 40, 41, 50, 50, 60])

In [67]:
np.sort(marks)[::-1]

array([60, 50, 50, 41, 40, 31, 30, 28])

In [68]:
np.argsort(marks)[::-1]

array([1, 2, 0, 6, 7, 5, 3, 4])

In [69]:
marks

array([50, 60, 50, 30, 28, 31, 41, 40])

In [73]:
a=np.array([90,20,30,40,50])

In [74]:
a

array([90, 20, 30, 40, 50])

In [75]:
a.argsort()

array([1, 2, 3, 4, 0])

In [76]:
a.argsort()[::-1]

array([0, 4, 3, 2, 1])

In [78]:
np.argsort(a)

array([1, 2, 3, 4, 0])

In [79]:
np.argsort(a)[::-1]

array([0, 4, 3, 2, 1])

In [80]:
np.sort(a)[::-1]

array([90, 50, 40, 30, 20])

In [98]:
b=np.where(a==30)[0]
print(b)

[2]


In [102]:
marks=np.array([34,54,89,23,45,67,88,90,12,49])
pass_index=np.where(marks>=40)[0]
fail_index=np.where(marks<40)[0]

print(pass_index)
print(fail_index)

[1 2 4 5 6 7 9]
[0 3 8]


In [108]:
import numpy as np
a=np.array([90,20,30,40,50])
result=np.where(a>=40)
print(result)
print(type(result))
reseult1=np.where(a>=40)[0]
print(reseult1)
print(type(reseult1))

(array([0, 3, 4]),)
<class 'tuple'>
[0 3 4]
<class 'numpy.ndarray'>
